import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

console.log("Job seeding function loaded")

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    console.log("Starting job seeding process...")

    const currentDate = new Date()
    const nextWeek = new Date()
    nextWeek.setDate(currentDate.getDate() + 7)

    // 25 South African job listings
    const southAfricanJobs = [
      {
        title: "Senior React Developer",
        company: "Discovery Health",
        location: "Sandton, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Build cutting-edge healthcare applications using React and modern web technologies.",
        requirements: ["5+ years React experience", "TypeScript proficiency", "Healthcare domain knowledge preferred"],
        benefits: ["Medical aid", "Discovery Miles", "Flexible working hours"],
        skills_required: ["React", "TypeScript", "Node.js", "GraphQL"],
        experience_level: "senior",
        application_url: "https://discovery.co.za/careers",
        source_website: "Discovery Careers",
        source_url: `https://discovery.co.za/careers/react-developer-${Date.now()}`,
        salary_min: 800000,
        salary_max: 1200000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Data Engineer",
        company: "Standard Bank",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Design and implement data pipelines for banking analytics and reporting.",
        requirements: ["3+ years data engineering", "Python/Scala experience", "Big data technologies"],
        benefits: ["Medical aid", "Pension fund", "Professional development"],
        skills_required: ["Python", "Apache Spark", "Kafka", "SQL"],
        experience_level: "mid-level",
        application_url: "https://standardbank.co.za/careers",
        source_website: "Standard Bank Careers",
        source_url: `https://standardbank.co.za/careers/data-engineer-${Date.now()}`,
        salary_min: 650000,
        salary_max: 950000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "DevOps Engineer",
        company: "Naspers",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Manage and optimize cloud infrastructure for global e-commerce platforms.",
        requirements: ["4+ years DevOps experience", "AWS/Azure expertise", "CI/CD pipelines"],
        benefits: ["Medical aid", "Remote work", "Annual bonus"],
        skills_required: ["AWS", "Docker", "Kubernetes", "Terraform"],
        experience_level: "senior",
        application_url: "https://naspers.com/careers",
        source_website: "Naspers Careers",
        source_url: `https://naspers.com/careers/devops-${Date.now()}`,
        salary_min: 700000,
        salary_max: 1100000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "UX/UI Designer",
        company: "Takealot",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Design intuitive and engaging user experiences for South Africa's leading e-commerce platform.",
        requirements: ["3+ years UX/UI design", "Figma/Sketch proficiency", "E-commerce experience"],
        benefits: ["Medical aid", "Staff discounts", "Flexible hours"],
        skills_required: ["Figma", "User Research", "Prototyping", "Design Systems"],
        experience_level: "mid-level",
        application_url: "https://takealot.com/careers",
        source_website: "Takealot Careers",
        source_url: `https://takealot.com/careers/ux-designer-${Date.now()}`,
        salary_min: 500000,
        salary_max: 750000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Mobile Developer (iOS/Android)",
        company: "Capitec Bank",
        location: "Stellenbosch, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Develop mobile banking applications used by millions of customers.",
        requirements: ["3+ years mobile development", "Swift or Kotlin", "Banking app experience"],
        benefits: ["Medical aid", "Performance bonuses", "Learning budget"],
        skills_required: ["Swift", "Kotlin", "React Native", "Mobile Security"],
        experience_level: "mid-level",
        application_url: "https://capitec.co.za/careers",
        source_website: "Capitec Careers",
        source_url: `https://capitec.co.za/careers/mobile-dev-${Date.now()}`,
        salary_min: 550000,
        salary_max: 850000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Machine Learning Engineer",
        company: "Amazon Web Services",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Build and deploy ML models for AWS cloud services.",
        requirements: ["5+ years ML experience", "Python expertise", "Deep learning frameworks"],
        benefits: ["Medical aid", "Stock options", "Relocation assistance"],
        skills_required: ["Python", "TensorFlow", "PyTorch", "AWS SageMaker"],
        experience_level: "senior",
        application_url: "https://amazon.jobs",
        source_website: "Amazon Jobs",
        source_url: `https://amazon.jobs/ml-engineer-${Date.now()}`,
        salary_min: 900000,
        salary_max: 1500000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Cybersecurity Analyst",
        company: "Old Mutual",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Protect financial systems and customer data from cyber threats.",
        requirements: ["3+ years security experience", "CISSP or CEH certification", "Financial sector knowledge"],
        benefits: ["Medical aid", "Pension fund", "Professional certifications"],
        skills_required: ["Network Security", "SIEM", "Incident Response", "Risk Assessment"],
        experience_level: "mid-level",
        application_url: "https://oldmutual.co.za/careers",
        source_website: "Old Mutual Careers",
        source_url: `https://oldmutual.co.za/careers/security-${Date.now()}`,
        salary_min: 600000,
        salary_max: 900000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Product Manager",
        company: "Yoco",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Drive product strategy for payment solutions for small businesses.",
        requirements: ["4+ years product management", "Fintech experience", "Agile methodology"],
        benefits: ["Medical aid", "Equity options", "Flexible work"],
        skills_required: ["Product Strategy", "Agile", "Analytics", "Fintech"],
        experience_level: "senior",
        application_url: "https://yoco.com/careers",
        source_website: "Yoco Careers",
        source_url: `https://yoco.com/careers/pm-${Date.now()}`,
        salary_min: 700000,
        salary_max: 1000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Backend Developer (Java)",
        company: "Absa Bank",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Develop robust backend services for digital banking platforms.",
        requirements: ["4+ years Java development", "Spring Boot", "Microservices architecture"],
        benefits: ["Medical aid", "Pension fund", "Annual leave"],
        skills_required: ["Java", "Spring Boot", "Microservices", "PostgreSQL"],
        experience_level: "mid-level",
        application_url: "https://absa.co.za/careers",
        source_website: "Absa Careers",
        source_url: `https://absa.co.za/careers/java-dev-${Date.now()}`,
        salary_min: 600000,
        salary_max: 900000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Business Intelligence Analyst",
        company: "Vodacom",
        location: "Midrand, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Analyze data and provide insights for telecommunications strategy.",
        requirements: ["3+ years BI experience", "SQL and visualization tools", "Telecom industry knowledge"],
        benefits: ["Medical aid", "Mobile allowance", "Performance bonuses"],
        skills_required: ["SQL", "Power BI", "Tableau", "Data Analysis"],
        experience_level: "mid-level",
        application_url: "https://vodacom.co.za/careers",
        source_website: "Vodacom Careers",
        source_url: `https://vodacom.co.za/careers/bi-analyst-${Date.now()}`,
        salary_min: 500000,
        salary_max: 750000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Full Stack Developer",
        company: "Investec",
        location: "Sandton, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Build full-stack applications for wealth management platforms.",
        requirements: ["4+ years full stack development", "React and .NET", "Financial services experience"],
        benefits: ["Medical aid", "Share scheme", "Gym membership"],
        skills_required: ["React", "C#", ".NET Core", "Azure"],
        experience_level: "senior",
        application_url: "https://investec.com/careers",
        source_website: "Investec Careers",
        source_url: `https://investec.com/careers/fullstack-${Date.now()}`,
        salary_min: 750000,
        salary_max: 1100000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "QA Automation Engineer",
        company: "Woolworths Holdings",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Implement automated testing frameworks for retail systems.",
        requirements: ["3+ years QA automation", "Selenium/Cypress", "CI/CD integration"],
        benefits: ["Medical aid", "Staff discounts", "Annual bonuses"],
        skills_required: ["Selenium", "Cypress", "JavaScript", "CI/CD"],
        experience_level: "mid-level",
        application_url: "https://woolworths.co.za/careers",
        source_website: "Woolworths Careers",
        source_url: `https://woolworths.co.za/careers/qa-${Date.now()}`,
        salary_min: 500000,
        salary_max: 750000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Cloud Architect",
        company: "Nedbank",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Design and implement cloud infrastructure for banking services.",
        requirements: ["6+ years cloud architecture", "Azure certification", "Financial services background"],
        benefits: ["Medical aid", "Pension fund", "Professional development"],
        skills_required: ["Azure", "Cloud Architecture", "DevOps", "Security"],
        experience_level: "senior",
        application_url: "https://nedbank.co.za/careers",
        source_website: "Nedbank Careers",
        source_url: `https://nedbank.co.za/careers/architect-${Date.now()}`,
        salary_min: 900000,
        salary_max: 1400000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Scrum Master",
        company: "FirstRand",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Facilitate agile ceremonies and remove blockers for development teams.",
        requirements: ["3+ years Scrum Master", "CSM certification", "Banking domain knowledge"],
        benefits: ["Medical aid", "Annual bonuses", "Remote work options"],
        skills_required: ["Scrum", "Agile", "Jira", "Facilitation"],
        experience_level: "mid-level",
        application_url: "https://firstrand.co.za/careers",
        source_website: "FirstRand Careers",
        source_url: `https://firstrand.co.za/careers/scrum-${Date.now()}`,
        salary_min: 550000,
        salary_max: 800000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Python Developer",
        company: "MTN Group",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Develop Python applications for telecom network management.",
        requirements: ["3+ years Python development", "Django/Flask", "API development"],
        benefits: ["Medical aid", "Mobile data allowance", "Learning budget"],
        skills_required: ["Python", "Django", "REST APIs", "PostgreSQL"],
        experience_level: "mid-level",
        application_url: "https://mtn.com/careers",
        source_website: "MTN Careers",
        source_url: `https://mtn.com/careers/python-dev-${Date.now()}`,
        salary_min: 550000,
        salary_max: 850000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Site Reliability Engineer",
        company: "Shoprite Holdings",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Ensure reliability and performance of retail systems infrastructure.",
        requirements: ["4+ years SRE experience", "Linux administration", "Monitoring tools"],
        benefits: ["Medical aid", "Staff discounts", "Performance bonuses"],
        skills_required: ["Linux", "Docker", "Prometheus", "Grafana"],
        experience_level: "senior",
        application_url: "https://shopriteholdings.co.za/careers",
        source_website: "Shoprite Careers",
        source_url: `https://shopriteholdings.co.za/careers/sre-${Date.now()}`,
        salary_min: 700000,
        salary_max: 1000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Data Scientist",
        company: "Sanlam",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Build predictive models for insurance and financial products.",
        requirements: ["4+ years data science", "Machine learning expertise", "Insurance domain"],
        benefits: ["Medical aid", "Pension fund", "Professional development"],
        skills_required: ["Python", "R", "Machine Learning", "Statistics"],
        experience_level: "senior",
        application_url: "https://sanlam.com/careers",
        source_website: "Sanlam Careers",
        source_url: `https://sanlam.com/careers/data-scientist-${Date.now()}`,
        salary_min: 750000,
        salary_max: 1200000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Frontend Developer (Angular)",
        company: "MultiChoice",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Develop streaming platform interfaces for millions of users.",
        requirements: ["3+ years Angular development", "TypeScript", "Video streaming experience"],
        benefits: ["Medical aid", "DStv subscription", "Annual bonuses"],
        skills_required: ["Angular", "TypeScript", "RxJS", "Video.js"],
        experience_level: "mid-level",
        application_url: "https://multichoice.com/careers",
        source_website: "MultiChoice Careers",
        source_url: `https://multichoice.com/careers/angular-dev-${Date.now()}`,
        salary_min: 550000,
        salary_max: 850000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Technical Writer",
        company: "IBM South Africa",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Create technical documentation for enterprise software solutions.",
        requirements: ["3+ years technical writing", "Software documentation", "API documentation"],
        benefits: ["Medical aid", "Learning opportunities", "Remote work"],
        skills_required: ["Technical Writing", "API Documentation", "Markdown", "Git"],
        experience_level: "mid-level",
        application_url: "https://ibm.com/careers",
        source_website: "IBM Careers",
        source_url: `https://ibm.com/careers/tech-writer-${Date.now()}`,
        salary_min: 450000,
        salary_max: 650000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Network Engineer",
        company: "Telkom",
        location: "Pretoria, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Design and maintain telecommunications network infrastructure.",
        requirements: ["4+ years network engineering", "CCNA/CCNP certification", "Telecom experience"],
        benefits: ["Medical aid", "Internet allowance", "Pension fund"],
        skills_required: ["Networking", "Cisco", "MPLS", "BGP"],
        experience_level: "senior",
        application_url: "https://telkom.co.za/careers",
        source_website: "Telkom Careers",
        source_url: `https://telkom.co.za/careers/network-eng-${Date.now()}`,
        salary_min: 650000,
        salary_max: 950000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Sales Engineer",
        company: "Microsoft South Africa",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Provide technical expertise for Azure cloud sales.",
        requirements: ["3+ years technical sales", "Azure knowledge", "Strong communication skills"],
        benefits: ["Medical aid", "Commission structure", "Training programs"],
        skills_required: ["Azure", "Sales", "Cloud Architecture", "Presentation"],
        experience_level: "mid-level",
        application_url: "https://microsoft.com/careers",
        source_website: "Microsoft Careers",
        source_url: `https://microsoft.com/careers/sales-eng-${Date.now()}`,
        salary_min: 600000,
        salary_max: 1000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Database Administrator",
        company: "Santam",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Manage and optimize insurance database systems.",
        requirements: ["4+ years DBA experience", "SQL Server expertise", "Performance tuning"],
        benefits: ["Medical aid", "Pension fund", "Flexible hours"],
        skills_required: ["SQL Server", "Oracle", "Database Optimization", "Backup & Recovery"],
        experience_level: "senior",
        application_url: "https://santam.co.za/careers",
        source_website: "Santam Careers",
        source_url: `https://santam.co.za/careers/dba-${Date.now()}`,
        salary_min: 650000,
        salary_max: 950000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "IT Project Manager",
        company: "Sasol",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Lead IT projects for energy and chemical manufacturing.",
        requirements: ["5+ years project management", "PMP certification", "Energy sector experience"],
        benefits: ["Medical aid", "Pension fund", "Company car"],
        skills_required: ["Project Management", "Agile", "Risk Management", "Stakeholder Management"],
        experience_level: "senior",
        application_url: "https://sasol.com/careers",
        source_website: "Sasol Careers",
        source_url: `https://sasol.com/careers/pm-${Date.now()}`,
        salary_min: 800000,
        salary_max: 1200000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Blockchain Developer",
        company: "Luno",
        location: "Cape Town, Western Cape, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Develop blockchain solutions for cryptocurrency exchange platform.",
        requirements: ["3+ years blockchain development", "Solidity/Web3", "Cryptocurrency knowledge"],
        benefits: ["Medical aid", "Crypto wallet bonus", "Remote work"],
        skills_required: ["Blockchain", "Solidity", "Web3.js", "Smart Contracts"],
        experience_level: "mid-level",
        application_url: "https://luno.com/careers",
        source_website: "Luno Careers",
        source_url: `https://luno.com/careers/blockchain-${Date.now()}`,
        salary_min: 700000,
        salary_max: 1100000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Systems Analyst",
        company: "Transnet",
        location: "Johannesburg, Gauteng, South Africa",
        job_type: "full-time",
        currency: "ZAR",
        description: "Analyze and improve logistics and transportation IT systems.",
        requirements: ["4+ years systems analysis", "Business analysis skills", "Logistics domain"],
        benefits: ["Medical aid", "Pension fund", "Annual leave"],
        skills_required: ["Business Analysis", "UML", "Requirements Gathering", "SQL"],
        experience_level: "senior",
        application_url: "https://transnet.net/careers",
        source_website: "Transnet Careers",
        source_url: `https://transnet.net/careers/analyst-${Date.now()}`,
        salary_min: 600000,
        salary_max: 900000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      }
    ]

    // 25 Nigerian job listings
    const nigerianJobs = [
      {
        title: "Full Stack Developer",
        company: "Flutterwave",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Develop end-to-end fintech solutions using modern web technologies.",
        requirements: ["4+ years full stack development", "React and Node.js", "Payment systems experience"],
        benefits: ["Health insurance", "Stock options", "Remote work flexibility"],
        skills_required: ["React", "Node.js", "MongoDB", "AWS"],
        experience_level: "mid-level",
        application_url: "https://flutterwave.com/careers",
        source_website: "Flutterwave Careers",
        source_url: `https://flutterwave.com/careers/fullstack-developer-${Date.now()}`,
        salary_min: 8000000,
        salary_max: 15000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Product Manager",
        company: "Paystack",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Drive product strategy and roadmap for payment infrastructure solutions.",
        requirements: ["3+ years product management", "Fintech experience", "Data-driven approach"],
        benefits: ["Health insurance", "Annual bonus", "Learning stipend"],
        skills_required: ["Product Management", "Analytics", "Fintech", "Agile"],
        experience_level: "senior",
        application_url: "https://paystack.com/careers",
        source_website: "Paystack Careers",
        source_url: `https://paystack.com/careers/product-manager-${Date.now()}`,
        salary_min: 12000000,
        salary_max: 20000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Backend Developer (Node.js)",
        company: "Interswitch",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Build scalable payment processing systems for Africa.",
        requirements: ["3+ years Node.js development", "Microservices", "Payment systems"],
        benefits: ["Health insurance", "Pension", "Training opportunities"],
        skills_required: ["Node.js", "Express", "Microservices", "Redis"],
        experience_level: "mid-level",
        application_url: "https://interswitch.com/careers",
        source_website: "Interswitch Careers",
        source_url: `https://interswitch.com/careers/node-dev-${Date.now()}`,
        salary_min: 7000000,
        salary_max: 12000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Mobile Developer (React Native)",
        company: "Kuda Bank",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Develop mobile banking apps for Nigeria's leading digital bank.",
        requirements: ["3+ years React Native", "Mobile app development", "Banking domain"],
        benefits: ["Health insurance", "Remote work", "Performance bonuses"],
        skills_required: ["React Native", "JavaScript", "Mobile Security", "Redux"],
        experience_level: "mid-level",
        application_url: "https://kuda.com/careers",
        source_website: "Kuda Careers",
        source_url: `https://kuda.com/careers/react-native-${Date.now()}`,
        salary_min: 7500000,
        salary_max: 13000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Data Engineer",
        company: "Andela",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Build data pipelines and analytics infrastructure for global clients.",
        requirements: ["4+ years data engineering", "Python/Scala", "Big data technologies"],
        benefits: ["Health insurance", "Remote work", "Learning budget"],
        skills_required: ["Python", "Apache Spark", "Airflow", "AWS"],
        experience_level: "senior",
        application_url: "https://andela.com/careers",
        source_website: "Andela Careers",
        source_url: `https://andela.com/careers/data-eng-${Date.now()}`,
        salary_min: 9000000,
        salary_max: 16000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "DevOps Engineer",
        company: "Sterling Bank",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Manage cloud infrastructure and CI/CD pipelines for banking systems.",
        requirements: ["3+ years DevOps", "AWS/Azure", "Kubernetes experience"],
        benefits: ["Health insurance", "Pension", "Annual bonuses"],
        skills_required: ["AWS", "Docker", "Kubernetes", "Terraform"],
        experience_level: "mid-level",
        application_url: "https://sterling.ng/careers",
        source_website: "Sterling Bank Careers",
        source_url: `https://sterling.ng/careers/devops-${Date.now()}`,
        salary_min: 7000000,
        salary_max: 12000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Frontend Developer (Vue.js)",
        company: "Jumia",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Build user interfaces for Africa's largest e-commerce platform.",
        requirements: ["3+ years Vue.js development", "E-commerce experience", "Performance optimization"],
        benefits: ["Health insurance", "Staff discounts", "Flexible hours"],
        skills_required: ["Vue.js", "JavaScript", "Webpack", "CSS"],
        experience_level: "mid-level",
        application_url: "https://jumia.com/careers",
        source_website: "Jumia Careers",
        source_url: `https://jumia.com/careers/vue-dev-${Date.now()}`,
        salary_min: 6500000,
        salary_max: 11000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Machine Learning Engineer",
        company: "Access Bank",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Develop ML models for fraud detection and customer insights.",
        requirements: ["4+ years ML engineering", "Python expertise", "Banking domain"],
        benefits: ["Health insurance", "Pension", "Professional development"],
        skills_required: ["Python", "TensorFlow", "Scikit-learn", "MLOps"],
        experience_level: "senior",
        application_url: "https://accessbankplc.com/careers",
        source_website: "Access Bank Careers",
        source_url: `https://accessbankplc.com/careers/ml-${Date.now()}`,
        salary_min: 9500000,
        salary_max: 17000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "UX Designer",
        company: "PiggyVest",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Design intuitive saving and investment experiences for millions of users.",
        requirements: ["3+ years UX design", "Fintech experience", "User research skills"],
        benefits: ["Health insurance", "Remote work", "Learning stipend"],
        skills_required: ["Figma", "User Research", "Prototyping", "Design Systems"],
        experience_level: "mid-level",
        application_url: "https://piggyvest.com/careers",
        source_website: "PiggyVest Careers",
        source_url: `https://piggyvest.com/careers/ux-${Date.now()}`,
        salary_min: 6000000,
        salary_max: 10000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Cybersecurity Engineer",
        company: "GTBank",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Secure banking infrastructure and protect customer data.",
        requirements: ["4+ years security engineering", "CISSP certification", "Banking experience"],
        benefits: ["Health insurance", "Pension", "Professional certifications"],
        skills_required: ["Network Security", "Penetration Testing", "SIEM", "Incident Response"],
        experience_level: "senior",
        application_url: "https://gtbank.com/careers",
        source_website: "GTBank Careers",
        source_url: `https://gtbank.com/careers/security-${Date.now()}`,
        salary_min: 8500000,
        salary_max: 15000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Cloud Architect",
        company: "MainOne",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Design cloud solutions for telecommunications infrastructure.",
        requirements: ["5+ years cloud architecture", "AWS/Azure certification", "Telecom background"],
        benefits: ["Health insurance", "Internet allowance", "Remote work"],
        skills_required: ["AWS", "Azure", "Cloud Architecture", "Networking"],
        experience_level: "senior",
        application_url: "https://mainone.net/careers",
        source_website: "MainOne Careers",
        source_url: `https://mainone.net/careers/architect-${Date.now()}`,
        salary_min: 10000000,
        salary_max: 18000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "QA Engineer",
        company: "Carbon",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Ensure quality of digital lending platform through automated testing.",
        requirements: ["3+ years QA automation", "Selenium/Cypress", "Fintech experience"],
        benefits: ["Health insurance", "Remote work", "Learning budget"],
        skills_required: ["Selenium", "Cypress", "JavaScript", "Test Automation"],
        experience_level: "mid-level",
        application_url: "https://carbon.co/careers",
        source_website: "Carbon Careers",
        source_url: `https://carbon.co/careers/qa-${Date.now()}`,
        salary_min: 6000000,
        salary_max: 10000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Software Architect",
        company: "Zenith Bank",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Design software architecture for core banking systems.",
        requirements: ["7+ years software development", "Architecture patterns", "Banking domain"],
        benefits: ["Health insurance", "Pension", "Company car"],
        skills_required: ["Software Architecture", "Microservices", "Java", "Cloud"],
        experience_level: "senior",
        application_url: "https://zenithbank.com/careers",
        source_website: "Zenith Bank Careers",
        source_url: `https://zenithbank.com/careers/architect-${Date.now()}`,
        salary_min: 12000000,
        salary_max: 22000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Technical Project Manager",
        company: "Airtel Nigeria",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Lead technical projects for telecommunications services.",
        requirements: ["5+ years project management", "PMP certification", "Telecom experience"],
        benefits: ["Health insurance", "Mobile allowance", "Performance bonuses"],
        skills_required: ["Project Management", "Agile", "Telecom", "Stakeholder Management"],
        experience_level: "senior",
        application_url: "https://airtel.com.ng/careers",
        source_website: "Airtel Careers",
        source_url: `https://airtel.com.ng/careers/pm-${Date.now()}`,
        salary_min: 9000000,
        salary_max: 16000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Business Analyst",
        company: "FCMB",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Analyze business requirements for digital banking initiatives.",
        requirements: ["3+ years business analysis", "Banking domain", "Agile methodology"],
        benefits: ["Health insurance", "Pension", "Annual bonuses"],
        skills_required: ["Business Analysis", "Requirements Gathering", "SQL", "Agile"],
        experience_level: "mid-level",
        application_url: "https://fcmb.com/careers",
        source_website: "FCMB Careers",
        source_url: `https://fcmb.com/careers/ba-${Date.now()}`,
        salary_min: 6500000,
        salary_max: 11000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Scrum Master",
        company: "OPay",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Facilitate agile development for fintech products.",
        requirements: ["3+ years Scrum Master", "CSM certification", "Fintech background"],
        benefits: ["Health insurance", "Remote work", "Learning budget"],
        skills_required: ["Scrum", "Agile", "Jira", "Facilitation"],
        experience_level: "mid-level",
        application_url: "https://opay.com/careers",
        source_website: "OPay Careers",
        source_url: `https://opay.com/careers/scrum-${Date.now()}`,
        salary_min: 6500000,
        salary_max: 11000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Python Developer",
        company: "MTN Nigeria",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Develop Python applications for telecom network management.",
        requirements: ["3+ years Python development", "Django/Flask", "Telecom systems"],
        benefits: ["Health insurance", "Data allowance", "Pension"],
        skills_required: ["Python", "Django", "REST APIs", "PostgreSQL"],
        experience_level: "mid-level",
        application_url: "https://mtnonline.com/careers",
        source_website: "MTN Careers",
        source_url: `https://mtnonline.com/careers/python-${Date.now()}`,
        salary_min: 6500000,
        salary_max: 11000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Data Analyst",
        company: "Bolt",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Analyze ride-hailing and delivery data to drive business decisions.",
        requirements: ["2+ years data analysis", "SQL and Python", "Visualization tools"],
        benefits: ["Health insurance", "Ride credits", "Flexible hours"],
        skills_required: ["SQL", "Python", "Tableau", "Statistics"],
        experience_level: "entry-level",
        application_url: "https://bolt.eu/careers",
        source_website: "Bolt Careers",
        source_url: `https://bolt.eu/careers/analyst-${Date.now()}`,
        salary_min: 5000000,
        salary_max: 8500000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Site Reliability Engineer",
        company: "Cowrywise",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Ensure reliability and performance of investment platform infrastructure.",
        requirements: ["4+ years SRE experience", "Kubernetes", "Monitoring tools"],
        benefits: ["Health insurance", "Investment allowance", "Remote work"],
        skills_required: ["Kubernetes", "Docker", "Prometheus", "Linux"],
        experience_level: "senior",
        application_url: "https://cowrywise.com/careers",
        source_website: "Cowrywise Careers",
        source_url: `https://cowrywise.com/careers/sre-${Date.now()}`,
        salary_min: 8000000,
        salary_max: 14000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Blockchain Developer",
        company: "Bundle Africa",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Build blockchain solutions for cryptocurrency trading platform.",
        requirements: ["3+ years blockchain development", "Solidity", "Web3 experience"],
        benefits: ["Health insurance", "Crypto bonuses", "Remote work"],
        skills_required: ["Blockchain", "Solidity", "Web3.js", "Ethereum"],
        experience_level: "mid-level",
        application_url: "https://bundle.africa/careers",
        source_website: "Bundle Careers",
        source_url: `https://bundle.africa/careers/blockchain-${Date.now()}`,
        salary_min: 7500000,
        salary_max: 13000000,
        remote_allowed: true,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Database Administrator",
        company: "Stanbic IBTC",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Manage database systems for banking operations.",
        requirements: ["4+ years DBA experience", "SQL Server/Oracle", "Performance tuning"],
        benefits: ["Health insurance", "Pension", "Annual leave"],
        skills_required: ["SQL Server", "Oracle", "Database Optimization", "Backup"],
        experience_level: "senior",
        application_url: "https://stanbicibtc.com/careers",
        source_website: "Stanbic IBTC Careers",
        source_url: `https://stanbicibtc.com/careers/dba-${Date.now()}`,
        salary_min: 7500000,
        salary_max: 13000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Solutions Architect",
        company: "SystemSpecs",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Design enterprise solutions for banking and payments systems.",
        requirements: ["6+ years solution architecture", "Enterprise patterns", "Banking domain"],
        benefits: ["Health insurance", "Pension", "Professional development"],
        skills_required: ["Solution Architecture", "Enterprise Integration", "APIs", "Cloud"],
        experience_level: "senior",
        application_url: "https://systemspecs.com.ng/careers",
        source_website: "SystemSpecs Careers",
        source_url: `https://systemspecs.com.ng/careers/architect-${Date.now()}`,
        salary_min: 10000000,
        salary_max: 18000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Technical Support Engineer",
        company: "9PSB",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Provide technical support for digital banking customers.",
        requirements: ["2+ years technical support", "Banking systems", "Customer service"],
        benefits: ["Health insurance", "Training", "Shift allowance"],
        skills_required: ["Technical Support", "Banking Systems", "Communication", "Troubleshooting"],
        experience_level: "entry-level",
        application_url: "https://9psb.com.ng/careers",
        source_website: "9PSB Careers",
        source_url: `https://9psb.com.ng/careers/support-${Date.now()}`,
        salary_min: 4500000,
        salary_max: 7500000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "iOS Developer",
        company: "Renmoney",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Develop iOS mobile apps for lending and savings platform.",
        requirements: ["3+ years iOS development", "Swift", "Mobile app security"],
        benefits: ["Health insurance", "Loan access", "Flexible hours"],
        skills_required: ["Swift", "iOS", "Core Data", "REST APIs"],
        experience_level: "mid-level",
        application_url: "https://renmoney.com/careers",
        source_website: "Renmoney Careers",
        source_url: `https://renmoney.com/careers/ios-${Date.now()}`,
        salary_min: 6500000,
        salary_max: 11000000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      },
      {
        title: "Network Administrator",
        company: "21st Century Technologies",
        location: "Lagos, Lagos State, Nigeria",
        job_type: "full-time",
        currency: "NGN",
        description: "Manage network infrastructure for enterprise clients.",
        requirements: ["3+ years network administration", "CCNA certification", "Enterprise networking"],
        benefits: ["Health insurance", "Training", "Pension"],
        skills_required: ["Networking", "Cisco", "Firewall", "VPN"],
        experience_level: "mid-level",
        application_url: "https://21ctng.com/careers",
        source_website: "21st Century Careers",
        source_url: `https://21ctng.com/careers/network-${Date.now()}`,
        salary_min: 5500000,
        salary_max: 9500000,
        remote_allowed: false,
        posted_date: currentDate.toISOString(),
        expires_date: nextWeek.toISOString(),
      }
    ]

    // Combine all jobs
    const allJobs = [...southAfricanJobs, ...nigerianJobs]

    // Insert new jobs
    const { data: insertedJobs, error: insertError } = await supabaseClient
      .from('jobs')
      .insert(allJobs)
      .select()

    if (insertError) {
      console.error('Error inserting jobs:', insertError)
      throw insertError
    }

    console.log(`Successfully seeded ${insertedJobs?.length || 0} job listings`)

    return new Response(
      JSON.stringify({
        success: true,
        insertedCount: insertedJobs?.length || 0,
        southAfricanCount: southAfricanJobs.length,
        nigerianCount: nigerianJobs.length,
        message: `Successfully seeded ${southAfricanJobs.length} South African jobs and ${nigerianJobs.length} Nigerian jobs`
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error in job-seeding function:', error)
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message 
      }),
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )
  }
})
