-- Insert South African job listings
INSERT INTO jobs (title, company, location, job_type, currency, description, requirements, benefits, skills_required, experience_level, application_url, company_logo_url, source_website, source_url, salary_min, salary_max, remote_allowed, posted_date, expires_date) VALUES
('Senior Software Engineer', 'Standard Bank', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Join our digital transformation team to build next-generation banking solutions using cutting-edge technology.', ARRAY['Bachelor''s degree in Computer Science', '5+ years software development experience', 'Experience with microservices architecture'], ARRAY['Medical aid', 'Pension fund', 'Performance bonuses', 'Flexible working hours'], ARRAY['Java', 'Spring Boot', 'Kubernetes', 'AWS'], 'senior', 'https://standardbank.co.za/careers', null, 'Standard Bank Careers', 'https://standardbank.co.za/careers/senior-software-engineer', 800000, 1200000, true, now() - interval '2 days', now() + interval '28 days'),

('Marketing Manager', 'Shoprite Holdings', 'Cape Town, Western Cape, South Africa', 'full-time', 'ZAR', 'Lead marketing campaigns across our retail network and drive customer engagement strategies.', ARRAY['Marketing degree or equivalent', '3+ years marketing experience', 'Digital marketing expertise'], ARRAY['Medical aid', 'Provident fund', 'Staff discounts'], ARRAY['Digital Marketing', 'Brand Management', 'Analytics'], 'mid-level', 'https://shopriteholdings.co.za/careers', null, 'Shoprite Careers', 'https://shopriteholdings.co.za/careers/marketing-manager', 600000, 800000, false, now() - interval '1 day', now() + interval '25 days'),

('Data Scientist', 'Discovery Limited', 'Sandton, Gauteng, South Africa', 'full-time', 'ZAR', 'Apply machine learning and statistical analysis to drive business insights and improve customer experiences.', ARRAY['Master''s in Data Science or related field', 'Python/R programming skills', 'Machine learning experience'], ARRAY['Medical aid', 'Life insurance', 'Vitality membership'], ARRAY['Python', 'Machine Learning', 'SQL', 'Statistics'], 'senior', 'https://discovery.co.za/careers', null, 'Discovery Careers', 'https://discovery.co.za/careers/data-scientist', 750000, 1100000, true, now() - interval '3 days', now() + interval '30 days'),

('Frontend Developer', 'Takealot', 'Cape Town, Western Cape, South Africa', 'full-time', 'ZAR', 'Build responsive e-commerce interfaces and enhance user experience across our platform.', ARRAY['3+ years frontend development', 'React.js experience', 'Mobile-first design approach'], ARRAY['Medical aid', 'Annual bonus', 'Remote work options'], ARRAY['React', 'TypeScript', 'CSS', 'JavaScript'], 'mid-level', 'https://takealot.com/careers', null, 'Takealot Careers', 'https://takealot.com/careers/frontend-developer', 500000, 700000, true, now() - interval '1 day', now() + interval '20 days'),

('Project Manager', 'Sasol', 'Secunda, Mpumalanga, South Africa', 'full-time', 'ZAR', 'Manage large-scale energy projects and coordinate cross-functional teams to deliver on strategic objectives.', ARRAY['PMP certification preferred', '5+ years project management', 'Energy sector experience'], ARRAY['Medical aid', 'Pension fund', 'Performance incentives'], ARRAY['Project Management', 'Agile', 'Risk Management'], 'senior', 'https://sasol.com/careers', null, 'Sasol Careers', 'https://sasol.com/careers/project-manager', 900000, 1300000, false, now() - interval '4 days', now() + interval '35 days'),

('UX Designer', 'Old Mutual', 'Cape Town, Western Cape, South Africa', 'contract', 'ZAR', 'Design intuitive digital experiences for our insurance and investment platforms.', ARRAY['UX/UI design degree', 'Portfolio of digital products', 'User research experience'], ARRAY['Contract rate negotiable', 'Flexible hours'], ARRAY['Figma', 'User Research', 'Prototyping'], 'mid-level', 'https://oldmutual.co.za/careers', null, 'Old Mutual Careers', 'https://oldmutual.co.za/careers/ux-designer', 400000, 600000, true, now() - interval '2 days', now() + interval '15 days'),

('Business Analyst', 'FNB', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Analyze business processes and requirements to drive digital banking innovation.', ARRAY['Business Analysis certification', 'Banking experience preferred', 'SQL knowledge'], ARRAY['Medical aid', 'Banking products', 'Study assistance'], ARRAY['Business Analysis', 'SQL', 'Process Mapping'], 'mid-level', 'https://fnb.co.za/careers', null, 'FNB Careers', 'https://fnb.co.za/careers/business-analyst', 550000, 750000, false, now() - interval '1 day', now() + interval '22 days'),

('DevOps Engineer', 'Capitec Bank', 'Stellenbosch, Western Cape, South Africa', 'full-time', 'ZAR', 'Build and maintain CI/CD pipelines and cloud infrastructure for banking applications.', ARRAY['3+ years DevOps experience', 'AWS/Azure certification', 'Docker and Kubernetes'], ARRAY['Medical aid', 'Performance bonus', 'Stock options'], ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform'], 'senior', 'https://capitecbank.co.za/careers', null, 'Capitec Careers', 'https://capitecbank.co.za/careers/devops-engineer', 700000, 950000, true, now() - interval '2 days', now() + interval '25 days'),

('Sales Manager', 'MTN Group', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Drive enterprise sales and manage key client relationships in the telecommunications sector.', ARRAY['Sales experience in telecommunications', 'Bachelor''s degree in Business', 'Proven track record'], ARRAY['Medical aid', 'Company car', 'Commission structure'], ARRAY['Sales', 'Account Management', 'Telecommunications'], 'senior', 'https://mtn.co.za/careers', null, 'MTN Careers', 'https://mtn.co.za/careers/sales-manager', 600000, 900000, false, now() - interval '3 days', now() + interval '28 days'),

('Quality Assurance Engineer', 'Dimension Data', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Ensure software quality through automated testing and quality assurance processes.', ARRAY['QA automation experience', 'Selenium or similar tools', 'API testing knowledge'], ARRAY['Medical aid', 'Training opportunities', 'Flexible working'], ARRAY['Selenium', 'API Testing', 'Test Automation'], 'mid-level', 'https://dimensiondata.com/careers', null, 'Dimension Data Careers', 'https://dimensiondata.com/careers/qa-engineer', 450000, 650000, true, now() - interval '1 day', now() + interval '20 days'),

('Financial Analyst', 'Nedbank', 'Sandton, Gauteng, South Africa', 'full-time', 'ZAR', 'Provide financial insights and analysis to support strategic business decisions.', ARRAY['CA(SA) or CFA preferred', '3+ years financial analysis', 'Advanced Excel skills'], ARRAY['Medical aid', 'Pension fund', 'Study leave'], ARRAY['Financial Analysis', 'Excel', 'Financial Modeling'], 'mid-level', 'https://nedbank.co.za/careers', null, 'Nedbank Careers', 'https://nedbank.co.za/careers/financial-analyst', 500000, 700000, false, now() - interval '2 days', now() + interval '30 days'),

('Mobile Developer', 'Mr Price Group', 'Durban, KwaZulu-Natal, South Africa', 'full-time', 'ZAR', 'Develop mobile applications for our retail and fashion brands.', ARRAY['Mobile development experience', 'iOS and Android platforms', 'React Native preferred'], ARRAY['Medical aid', 'Staff discounts', 'Casual dress code'], ARRAY['React Native', 'iOS', 'Android'], 'mid-level', 'https://mrpricegroup.com/careers', null, 'Mr Price Careers', 'https://mrpricegroup.com/careers/mobile-developer', 480000, 680000, true, now() - interval '1 day', now() + interval '25 days'),

('HR Manager', 'Anglo American', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Lead human resources initiatives and talent management for mining operations.', ARRAY['HR degree or equivalent', 'Mining industry experience', 'HRIS system knowledge'], ARRAY['Medical aid', 'Mining allowances', 'Pension fund'], ARRAY['Human Resources', 'Talent Management', 'HRIS'], 'senior', 'https://angloamerican.com/careers', null, 'Anglo American Careers', 'https://angloamerican.com/careers/hr-manager', 650000, 850000, false, now() - interval '4 days', now() + interval '32 days'),

('Cybersecurity Specialist', 'Absa Group', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Protect banking infrastructure and implement security measures across digital platforms.', ARRAY['Cybersecurity certification', 'Incident response experience', 'Network security knowledge'], ARRAY['Medical aid', 'Security clearance bonus', 'Training budget'], ARRAY['Cybersecurity', 'Incident Response', 'Network Security'], 'senior', 'https://absa.co.za/careers', null, 'Absa Careers', 'https://absa.co.za/careers/cybersecurity-specialist', 800000, 1200000, false, now() - interval '2 days', now() + interval '28 days'),

('Product Manager', 'Naspers', 'Cape Town, Western Cape, South Africa', 'full-time', 'ZAR', 'Drive product strategy and roadmap for digital platforms and consumer technology.', ARRAY['Product management experience', 'Tech background preferred', 'Agile methodology knowledge'], ARRAY['Medical aid', 'Stock options', 'Innovation time'], ARRAY['Product Management', 'Agile', 'Analytics'], 'senior', 'https://naspers.com/careers', null, 'Naspers Careers', 'https://naspers.com/careers/product-manager', 750000, 1100000, true, now() - interval '3 days', now() + interval '30 days'),

('Supply Chain Analyst', 'Woolworths Holdings', 'Cape Town, Western Cape, South Africa', 'full-time', 'ZAR', 'Optimize supply chain operations and analyze logistics performance.', ARRAY['Supply chain qualification', 'Data analysis skills', 'ERP system experience'], ARRAY['Medical aid', 'Staff discounts', 'Performance bonus'], ARRAY['Supply Chain', 'Data Analysis', 'ERP Systems'], 'mid-level', 'https://woolworthsholdings.co.za/careers', null, 'Woolworths Careers', 'https://woolworthsholdings.co.za/careers/supply-chain-analyst', 420000, 580000, false, now() - interval '1 day', now() + interval '25 days'),

('Cloud Architect', 'Telkom', 'Centurion, Gauteng, South Africa', 'full-time', 'ZAR', 'Design and implement cloud infrastructure solutions for telecommunications services.', ARRAY['Cloud architecture experience', 'AWS/Azure expertise', 'Enterprise solution design'], ARRAY['Medical aid', 'Company benefits', 'Professional development'], ARRAY['Cloud Architecture', 'AWS', 'Azure'], 'senior', 'https://telkom.co.za/careers', null, 'Telkom Careers', 'https://telkom.co.za/careers/cloud-architect', 850000, 1250000, true, now() - interval '2 days', now() + interval '35 days'),

('Content Marketing Specialist', 'Media24', 'Cape Town, Western Cape, South Africa', 'contract', 'ZAR', 'Create engaging content across digital platforms and manage social media presence.', ARRAY['Content marketing experience', 'Social media expertise', 'Creative writing skills'], ARRAY['Flexible working', 'Creative environment', 'Project-based rates'], ARRAY['Content Marketing', 'Social Media', 'Copywriting'], 'mid-level', 'https://media24.com/careers', null, 'Media24 Careers', 'https://media24.com/careers/content-marketing', 300000, 450000, true, now() - interval '1 day', now() + interval '15 days'),

('Operations Manager', 'Massmart', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Oversee retail operations and drive operational excellence across store networks.', ARRAY['Operations management experience', 'Retail background preferred', 'Leadership skills'], ARRAY['Medical aid', 'Performance incentives', 'Career progression'], ARRAY['Operations Management', 'Retail', 'Leadership'], 'senior', 'https://massmart.co.za/careers', null, 'Massmart Careers', 'https://massmart.co.za/careers/operations-manager', 550000, 750000, false, now() - interval '3 days', now() + interval '28 days'),

('Database Administrator', 'Bidvest Group', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Manage database systems and ensure data integrity across business operations.', ARRAY['DBA certification', 'SQL Server/Oracle experience', 'Database optimization'], ARRAY['Medical aid', 'Training opportunities', 'Flexible hours'], ARRAY['SQL Server', 'Oracle', 'Database Administration'], 'mid-level', 'https://bidvest.co.za/careers', null, 'Bidvest Careers', 'https://bidvest.co.za/careers/database-administrator', 480000, 680000, false, now() - interval '2 days', now() + interval '25 days'),

('Legal Counsel', 'Sanlam', 'Cape Town, Western Cape, South Africa', 'full-time', 'ZAR', 'Provide legal advice and support for insurance and financial services operations.', ARRAY['LLB degree', 'Admitted attorney', 'Financial services experience'], ARRAY['Medical aid', 'Legal indemnity', 'Professional development'], ARRAY['Legal', 'Financial Services', 'Compliance'], 'senior', 'https://sanlam.co.za/careers', null, 'Sanlam Careers', 'https://sanlam.co.za/careers/legal-counsel', 700000, 950000, false, now() - interval '4 days', now() + interval '32 days'),

('Network Engineer', 'Vodacom', 'Midrand, Gauteng, South Africa', 'full-time', 'ZAR', 'Design and maintain telecommunications network infrastructure and optimize performance.', ARRAY['Network engineering degree', 'Cisco certification preferred', 'Telecom experience'], ARRAY['Medical aid', 'Network allowances', 'Training budget'], ARRAY['Network Engineering', 'Cisco', 'Telecommunications'], 'mid-level', 'https://vodacom.co.za/careers', null, 'Vodacom Careers', 'https://vodacom.co.za/careers/network-engineer', 520000, 720000, false, now() - interval '1 day', now() + interval '22 days'),

('Business Development Manager', 'Tiger Brands', 'Johannesburg, Gauteng, South Africa', 'full-time', 'ZAR', 'Drive business growth and develop strategic partnerships in the FMCG sector.', ARRAY['Business development experience', 'FMCG background preferred', 'Strategic thinking skills'], ARRAY['Medical aid', 'Company car', 'Performance bonus'], ARRAY['Business Development', 'FMCG', 'Strategic Planning'], 'senior', 'https://tigerbrands.co.za/careers', null, 'Tiger Brands Careers', 'https://tigerbrands.co.za/careers/business-development', 600000, 800000, false, now() - interval '2 days', now() + interval '30 days'),

('Full Stack Developer', 'Momentum Metropolitan', 'Centurion, Gauteng, South Africa', 'full-time', 'ZAR', 'Develop end-to-end web applications for insurance and investment platforms.', ARRAY['Full stack development experience', '.NET or Java preferred', 'Database design skills'], ARRAY['Medical aid', 'Pension fund', 'Remote work options'], ARRAY['Full Stack Development', '.NET', 'SQL'], 'mid-level', 'https://momentum.co.za/careers', null, 'Momentum Careers', 'https://momentum.co.za/careers/full-stack-developer', 500000, 700000, true, now() - interval '1 day', now() + interval '25 days'),

('Research Analyst', 'University of Cape Town', 'Cape Town, Western Cape, South Africa', 'contract', 'ZAR', 'Conduct academic research and data analysis for various research projects.', ARRAY['Master''s degree preferred', 'Research experience', 'Statistical analysis skills'], ARRAY['University benefits', 'Research support', 'Academic environment'], ARRAY['Research', 'Statistical Analysis', 'Academic Writing'], 'junior', 'https://uct.ac.za/careers', null, 'UCT Careers', 'https://uct.ac.za/careers/research-analyst', 350000, 500000, false, now() - interval '3 days', now() + interval '20 days');

-- Insert Nigerian job listings
INSERT INTO jobs (title, company, location, job_type, currency, description, requirements, benefits, skills_required, experience_level, application_url, company_logo_url, source_website, source_url, salary_min, salary_max, remote_allowed, posted_date, expires_date) VALUES
('Software Engineer', 'Interswitch', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Build innovative fintech solutions and payment systems for Africa''s leading payment company.', ARRAY['Bachelor''s in Computer Science', '3+ years software development', 'Experience with microservices'], ARRAY['Health insurance', 'Pension scheme', 'Performance bonus', 'Learning budget'], ARRAY['Java', 'Spring Boot', 'Microservices', 'REST APIs'], 'mid-level', 'https://interswitch.com/careers', null, 'Interswitch Careers', 'https://interswitch.com/careers/software-engineer', 8000000, 12000000, true, now() - interval '1 day', now() + interval '30 days'),

('Product Manager', 'Flutterwave', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Drive product strategy for payment solutions across African markets.', ARRAY['Product management experience', 'Fintech background preferred', 'Data-driven decision making'], ARRAY['Health insurance', 'Stock options', 'Remote work allowance'], ARRAY['Product Management', 'Analytics', 'Fintech'], 'senior', 'https://flutterwave.com/careers', null, 'Flutterwave Careers', 'https://flutterwave.com/careers/product-manager', 15000000, 25000000, true, now() - interval '2 days', now() + interval '25 days'),

('Data Scientist', 'Andela', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Apply machine learning to solve complex business problems and drive insights.', ARRAY['Master''s in Data Science', 'Python/R proficiency', 'Machine learning experience'], ARRAY['Health insurance', 'Learning stipend', 'Flexible working'], ARRAY['Python', 'Machine Learning', 'SQL', 'Statistics'], 'senior', 'https://andela.com/careers', null, 'Andela Careers', 'https://andela.com/careers/data-scientist', 12000000, 18000000, true, now() - interval '1 day', now() + interval '28 days'),

('Frontend Developer', 'Paystack', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Create beautiful and functional user interfaces for payment platforms.', ARRAY['Frontend development experience', 'React.js expertise', 'UI/UX sensibility'], ARRAY['Health insurance', 'Annual bonus', 'Tech allowance'], ARRAY['React', 'JavaScript', 'TypeScript', 'CSS'], 'mid-level', 'https://paystack.com/careers', null, 'Paystack Careers', 'https://paystack.com/careers/frontend-developer', 7000000, 11000000, true, now() - interval '3 days', now() + interval '22 days'),

('Marketing Manager', 'Jumia', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Lead digital marketing campaigns for Africa''s largest e-commerce platform.', ARRAY['Marketing degree', 'E-commerce experience', 'Digital marketing expertise'], ARRAY['Health insurance', 'Performance bonus', 'Employee discounts'], ARRAY['Digital Marketing', 'E-commerce', 'Analytics'], 'senior', 'https://jumia.com.ng/careers', null, 'Jumia Careers', 'https://jumia.com.ng/careers/marketing-manager', 8000000, 12000000, false, now() - interval '2 days', now() + interval '30 days'),

('DevOps Engineer', 'Konga', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Manage cloud infrastructure and deployment pipelines for e-commerce operations.', ARRAY['DevOps experience', 'AWS/Azure knowledge', 'Container orchestration'], ARRAY['Health insurance', 'Tech budget', 'Remote work options'], ARRAY['AWS', 'Docker', 'Kubernetes', 'CI/CD'], 'mid-level', 'https://konga.com/careers', null, 'Konga Careers', 'https://konga.com/careers/devops-engineer', 9000000, 13000000, true, now() - interval '1 day', now() + interval '25 days'),

('Business Analyst', 'First Bank Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Analyze business processes and drive digital transformation initiatives in banking.', ARRAY['Business analysis certification', 'Banking experience', 'Process improvement'], ARRAY['Health insurance', 'Pension scheme', 'Banking benefits'], ARRAY['Business Analysis', 'Process Mapping', 'Banking'], 'mid-level', 'https://firstbanknigeria.com/careers', null, 'First Bank Careers', 'https://firstbanknigeria.com/careers/business-analyst', 6000000, 9000000, false, now() - interval '2 days', now() + interval '28 days'),

('Mobile Developer', 'GTBank', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Develop mobile banking applications and enhance digital banking experiences.', ARRAY['Mobile development experience', 'Banking app experience', 'Security best practices'], ARRAY['Health insurance', 'Pension fund', 'Professional development'], ARRAY['React Native', 'iOS', 'Android', 'Security'], 'senior', 'https://gtbank.com/careers', null, 'GTBank Careers', 'https://gtbank.com/careers/mobile-developer', 8500000, 12500000, false, now() - interval '1 day', now() + interval '30 days'),

('Sales Manager', 'MTN Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Drive enterprise sales and manage key accounts in telecommunications.', ARRAY['Sales experience in telecom', 'Account management skills', 'Target achievement record'], ARRAY['Health insurance', 'Commission structure', 'Company car'], ARRAY['Sales', 'Telecommunications', 'Account Management'], 'senior', 'https://mtnnigeria.net/careers', null, 'MTN Nigeria Careers', 'https://mtnnigeria.net/careers/sales-manager', 7000000, 11000000, false, now() - interval '3 days', now() + interval '25 days'),

('Quality Assurance Engineer', 'SystemSpecs', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Ensure software quality through comprehensive testing of fintech applications.', ARRAY['QA automation experience', 'Testing frameworks', 'API testing'], ARRAY['Health insurance', 'Training opportunities', 'Flexible hours'], ARRAY['Selenium', 'API Testing', 'Test Automation'], 'mid-level', 'https://systemspecs.com.ng/careers', null, 'SystemSpecs Careers', 'https://systemspecs.com.ng/careers/qa-engineer', 5500000, 8000000, true, now() - interval '2 days', now() + interval '22 days'),

('Financial Analyst', 'Access Bank', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Provide financial analysis and insights to support strategic business decisions.', ARRAY['Finance/Accounting degree', 'Banking experience', 'Financial modeling'], ARRAY['Health insurance', 'Pension scheme', 'Performance bonus'], ARRAY['Financial Analysis', 'Excel', 'Banking'], 'mid-level', 'https://accessbankplc.com/careers', null, 'Access Bank Careers', 'https://accessbankplc.com/careers/financial-analyst', 6000000, 9000000, false, now() - interval '1 day', now() + interval '28 days'),

('UX Designer', 'Cowrywise', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Design user experiences for investment and savings applications.', ARRAY['UX design experience', 'Fintech background preferred', 'User research skills'], ARRAY['Health insurance', 'Design budget', 'Remote work'], ARRAY['UX Design', 'Figma', 'User Research'], 'mid-level', 'https://cowrywise.com/careers', null, 'Cowrywise Careers', 'https://cowrywise.com/careers/ux-designer', 6500000, 9500000, true, now() - interval '2 days', now() + interval '25 days'),

('Backend Developer', 'PiggyVest', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Build scalable backend systems for savings and investment platforms.', ARRAY['Backend development experience', 'API design', 'Database management'], ARRAY['Health insurance', 'Stock options', 'Learning budget'], ARRAY['Node.js', 'Python', 'PostgreSQL', 'APIs'], 'senior', 'https://piggyvest.com/careers', null, 'PiggyVest Careers', 'https://piggyvest.com/careers/backend-developer', 8000000, 12000000, true, now() - interval '1 day', now() + interval '30 days'),

('Project Manager', 'Dangote Group', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Manage large-scale industrial projects across manufacturing and energy sectors.', ARRAY['PMP certification', 'Industrial experience', 'Project leadership'], ARRAY['Health insurance', 'Housing allowance', 'Performance incentives'], ARRAY['Project Management', 'Industrial', 'Leadership'], 'senior', 'https://dangote.com/careers', null, 'Dangote Careers', 'https://dangote.com/careers/project-manager', 10000000, 15000000, false, now() - interval '4 days', now() + interval '35 days'),

('Cybersecurity Specialist', 'Zenith Bank', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Protect banking systems and implement security measures for digital platforms.', ARRAY['Cybersecurity certification', 'Banking security experience', 'Incident response'], ARRAY['Health insurance', 'Security clearance bonus', 'Professional development'], ARRAY['Cybersecurity', 'Banking Security', 'Incident Response'], 'senior', 'https://zenithbank.com/careers', null, 'Zenith Bank Careers', 'https://zenithbank.com/careers/cybersecurity', 9000000, 14000000, false, now() - interval '2 days', now() + interval '28 days'),

('Content Creator', 'Nollywood Studios', 'Lagos, Lagos State, Nigeria', 'contract', 'NGN', 'Create engaging video content and manage social media presence for entertainment.', ARRAY['Content creation experience', 'Video editing skills', 'Social media expertise'], ARRAY['Creative environment', 'Project rates', 'Networking opportunities'], ARRAY['Content Creation', 'Video Editing', 'Social Media'], 'mid-level', 'https://nollywoodstudios.com/careers', null, 'Nollywood Careers', 'https://nollywoodstudios.com/careers/content-creator', 3000000, 5000000, true, now() - interval '1 day', now() + interval '15 days'),

('Operations Manager', 'Nigerian Breweries', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Oversee manufacturing operations and drive operational excellence.', ARRAY['Operations management experience', 'Manufacturing background', 'Leadership skills'], ARRAY['Health insurance', 'Housing allowance', 'Career progression'], ARRAY['Operations Management', 'Manufacturing', 'Leadership'], 'senior', 'https://nbplc.com/careers', null, 'Nigerian Breweries Careers', 'https://nbplc.com/careers/operations-manager', 8000000, 12000000, false, now() - interval '3 days', now() + interval '32 days'),

('Database Administrator', 'Ecobank Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Manage database systems and ensure data integrity for banking operations.', ARRAY['DBA certification', 'Banking database experience', 'Performance optimization'], ARRAY['Health insurance', 'Pension fund', 'Technical training'], ARRAY['Oracle', 'SQL Server', 'Database Administration'], 'mid-level', 'https://ecobank.com/ng/careers', null, 'Ecobank Careers', 'https://ecobank.com/ng/careers/database-admin', 7000000, 10000000, false, now() - interval '2 days', now() + interval '25 days'),

('Legal Counsel', 'Nigerian National Petroleum Corporation', 'Abuja, Federal Capital Territory, Nigeria', 'full-time', 'NGN', 'Provide legal advice and support for oil and gas operations.', ARRAY['LLB degree', 'Oil & gas experience', 'Corporate law expertise'], ARRAY['Health insurance', 'Housing allowance', 'Federal benefits'], ARRAY['Corporate Law', 'Oil & Gas', 'Compliance'], 'senior', 'https://nnpc.gov.ng/careers', null, 'NNPC Careers', 'https://nnpc.gov.ng/careers/legal-counsel', 12000000, 18000000, false, now() - interval '4 days', now() + interval '35 days'),

('Network Engineer', 'Airtel Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Design and maintain telecommunications network infrastructure.', ARRAY['Network engineering degree', 'Telecom experience', 'Cisco certification'], ARRAY['Health insurance', 'Technical allowances', 'Training opportunities'], ARRAY['Network Engineering', 'Telecommunications', 'Cisco'], 'mid-level', 'https://airtel.com.ng/careers', null, 'Airtel Nigeria Careers', 'https://airtel.com.ng/careers/network-engineer', 6500000, 9500000, false, now() - interval '1 day', now() + interval '25 days'),

('Business Development Manager', 'Unilever Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Drive business growth and develop strategic partnerships in FMCG sector.', ARRAY['Business development experience', 'FMCG background', 'Strategic planning'], ARRAY['Health insurance', 'Company car', 'Performance bonus'], ARRAY['Business Development', 'FMCG', 'Strategic Planning'], 'senior', 'https://unilever.com.ng/careers', null, 'Unilever Nigeria Careers', 'https://unilever.com.ng/careers/business-development', 9000000, 13000000, false, now() - interval '2 days', now() + interval '30 days'),

('Full Stack Developer', 'Leadway Assurance', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Develop web applications for insurance and financial services.', ARRAY['Full stack experience', 'Insurance tech preferred', 'Database design'], ARRAY['Health insurance', 'Professional development', 'Remote options'], ARRAY['Full Stack Development', 'JavaScript', 'SQL'], 'mid-level', 'https://leadway.com/careers', null, 'Leadway Careers', 'https://leadway.com/careers/full-stack-developer', 7500000, 11000000, true, now() - interval '1 day', now() + interval '28 days'),

('Research Analyst', 'University of Lagos', 'Lagos, Lagos State, Nigeria', 'contract', 'NGN', 'Conduct academic research and data analysis for various projects.', ARRAY['Master''s degree', 'Research experience', 'Statistical analysis'], ARRAY['Academic benefits', 'Research support', 'Flexible schedule'], ARRAY['Research', 'Statistical Analysis', 'Academic Writing'], 'junior', 'https://unilag.edu.ng/careers', null, 'UNILAG Careers', 'https://unilag.edu.ng/careers/research-analyst', 4000000, 6000000, false, now() - interval '3 days', now() + interval '20 days'),

('Cloud Engineer', 'Microsoft Nigeria', 'Lagos, Lagos State, Nigeria', 'full-time', 'NGN', 'Design and implement cloud solutions for enterprise clients.', ARRAY['Cloud engineering experience', 'Azure certification', 'Enterprise solutions'], ARRAY['Health insurance', 'Stock options', 'Learning budget'], ARRAY['Azure', 'Cloud Architecture', 'Enterprise Solutions'], 'senior', 'https://microsoft.com/careers', null, 'Microsoft Careers', 'https://microsoft.com/careers/cloud-engineer-nigeria', 15000000, 22000000, true, now() - interval '2 days', now() + interval '30 days'),

('HR Manager', 'Shell Nigeria', 'Port Harcourt, Rivers State, Nigeria', 'full-time', 'NGN', 'Lead human resources initiatives for oil and gas operations.', ARRAY['HR degree', 'Oil & gas experience', 'Talent management'], ARRAY['Health insurance', 'Expatriate benefits', 'Pension fund'], ARRAY['Human Resources', 'Oil & Gas', 'Talent Management'], 'senior', 'https://shell.com.ng/careers', null, 'Shell Nigeria Careers', 'https://shell.com.ng/careers/hr-manager', 11000000, 16000000, false, now() - interval '4 days', now() + interval '35 days');