-- Insert mock job data for demonstration
INSERT INTO public.jobs (title, company, location, job_type, salary_min, salary_max, currency, description, skills_required, experience_level, remote_allowed, application_url, source_website, source_url) VALUES 
('Senior Software Engineer', 'TechSA Solutions', 'Johannesburg, South Africa', 'Full-time', 450000, 650000, 'ZAR', 'Join our dynamic team building innovative fintech solutions for the African market. Work with cutting-edge technologies including React, Node.js, and cloud platforms. We''re looking for passionate developers who want to make an impact in the fintech space.', ARRAY['JavaScript', 'React', 'Node.js', 'TypeScript', 'AWS'], 'Senior', true, 'https://techsa.co.za/careers', 'LinkedIn', 'https://linkedin.com/jobs/123'),

('Digital Marketing Manager', 'Lagos Digital Hub', 'Lagos, Nigeria', 'Full-time', 2400000, 3600000, 'NGN', 'Lead digital marketing initiatives for growing tech startups across West Africa. Drive brand awareness and customer acquisition through innovative campaigns, SEO optimization, and social media strategies.', ARRAY['Digital Marketing', 'SEO', 'Social Media', 'Google Ads', 'Analytics'], 'Mid-level', false, 'https://lagosdigital.com/careers', 'Indeed', 'https://indeed.com/jobs/456'),

('Data Scientist', 'African Analytics Co', 'Cape Town, South Africa', 'Full-time', 380000, 550000, 'ZAR', 'Analyze large datasets to drive business decisions in the retail and e-commerce space. Work with machine learning models, statistical analysis, and data visualization tools to uncover insights.', ARRAY['Python', 'Machine Learning', 'SQL', 'Tableau', 'Statistics'], 'Mid-level', true, 'https://africananalytics.com/jobs', 'Glassdoor', 'https://glassdoor.com/jobs/789'),

('Product Manager', 'Fintech Innovation Ltd', 'Remote (Africa)', 'Full-time', 420000, 580000, 'ZAR', 'Drive product strategy and roadmap for our mobile banking platform serving millions of users across Africa. Collaborate with engineering, design, and business teams to deliver world-class financial products.', ARRAY['Product Management', 'Agile', 'User Research', 'Analytics', 'Fintech'], 'Senior', true, 'https://fintechinnovation.africa/careers', 'LinkedIn', 'https://linkedin.com/jobs/101112'),

('UX/UI Designer', 'Creative Studios SA', 'Cape Town, South Africa', 'Full-time', 280000, 420000, 'ZAR', 'Design beautiful and intuitive user experiences for web and mobile applications. Work closely with product teams to create user-centered designs that solve real problems for African users.', ARRAY['UI/UX Design', 'Figma', 'Sketch', 'Prototyping', 'User Research'], 'Mid-level', false, 'https://creativestudios.co.za/jobs', 'LinkedIn', 'https://linkedin.com/jobs/131415'),

('DevOps Engineer', 'Cloud Solutions Africa', 'Johannesburg, South Africa', 'Full-time', 400000, 600000, 'ZAR', 'Build and maintain scalable cloud infrastructure for enterprise clients across Africa. Expertise in containerization, CI/CD pipelines, and infrastructure as code required.', ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'], 'Senior', true, 'https://cloudsolutions.africa/careers', 'Indeed', 'https://indeed.com/jobs/161718'),

('Sales Manager', 'Tech Sales Pro', 'Lagos, Nigeria', 'Full-time', 3000000, 4500000, 'NGN', 'Lead a high-performing sales team selling B2B SaaS solutions to enterprises across West Africa. Drive revenue growth and build strategic partnerships with key clients.', ARRAY['Sales', 'B2B', 'SaaS', 'CRM', 'Negotiation'], 'Senior', false, 'https://techsalespro.ng/careers', 'Glassdoor', 'https://glassdoor.com/jobs/192021'),

('Frontend Developer', 'StartupHub Africa', 'Remote (Africa)', 'Full-time', 320000, 480000, 'ZAR', 'Build responsive web applications using modern JavaScript frameworks. Join a fast-growing startup creating solutions for the African market with a focus on mobile-first experiences.', ARRAY['JavaScript', 'React', 'TypeScript', 'CSS', 'Mobile-first'], 'Mid-level', true, 'https://startuphub.africa/jobs', 'LinkedIn', 'https://linkedin.com/jobs/222324'),

('Business Analyst', 'Enterprise Solutions Ltd', 'Pretoria, South Africa', 'Full-time', 300000, 450000, 'ZAR', 'Analyze business processes and requirements to drive digital transformation initiatives. Work with stakeholders to identify opportunities for process improvement and system optimization.', ARRAY['Business Analysis', 'SQL', 'Power BI', 'Process Mapping', 'Stakeholder Management'], 'Mid-level', false, 'https://enterprisesolutions.co.za/careers', 'Indeed', 'https://indeed.com/jobs/252627'),

('Mobile Developer', 'Mobile First Tech', 'Durban, South Africa', 'Full-time', 340000, 520000, 'ZAR', 'Develop native and cross-platform mobile applications for iOS and Android. Focus on creating high-quality mobile experiences for financial services and e-commerce platforms.', ARRAY['React Native', 'iOS', 'Android', 'JavaScript', 'Mobile Development'], 'Mid-level', true, 'https://mobilefirst.tech/jobs', 'Glassdoor', 'https://glassdoor.com/jobs/282930'),

('Cybersecurity Analyst', 'SecureAfrica', 'Johannesburg, South Africa', 'Full-time', 380000, 580000, 'ZAR', 'Protect enterprise systems and data from cyber threats. Monitor security incidents, conduct vulnerability assessments, and implement security best practices across our client base.', ARRAY['Cybersecurity', 'Network Security', 'Incident Response', 'Risk Assessment', 'CISSP'], 'Senior', false, 'https://secureafrica.com/careers', 'LinkedIn', 'https://linkedin.com/jobs/313233'),

('AI/ML Engineer', 'AI Innovations Africa', 'Cape Town, South Africa', 'Full-time', 450000, 680000, 'ZAR', 'Develop and deploy machine learning models for various applications including computer vision, natural language processing, and predictive analytics. Work on cutting-edge AI projects serving the African continent.', ARRAY['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Deep Learning'], 'Senior', true, 'https://aiinnovations.africa/jobs', 'Indeed', 'https://indeed.com/jobs/343536');