name: Cleanup Old Job Listings

on:
  # Daily cleanup at 3 AM UTC
  schedule:
    - cron: '0 3 * * *'
  # Manual trigger
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "cleanup-jobs" to confirm cleanup'
        required: true
        default: ''

jobs:
  cleanup-jobs:
    name: Remove Jobs Older Than 30 Days
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate confirmation (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "cleanup-jobs" ]; then
            echo "❌ Confirmation failed. Please type 'cleanup-jobs' to confirm."
            exit 1
          fi
          echo "✅ Confirmation validated"
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link Supabase project
        run: |
          supabase link --project-ref ${{ secrets.VITE_SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Deploy job-cleanup function (if needed)
        run: |
          supabase functions deploy job-cleanup
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Invoke job-cleanup function
        run: |
          echo "🧹 Cleaning up old job listings..."
          response=$(curl -s -X POST \
            "${{ secrets.VITE_SUPABASE_URL }}/functions/v1/job-cleanup" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json")
          
          echo "Response: $response"
          
          # Check if response contains success
          if echo "$response" | grep -q "success.*true"; then
            echo "✅ Old job listings cleaned up successfully!"
          else
            echo "⚠️  Cleanup completed with warnings or no jobs to clean"
          fi
      
      - name: Summary
        run: |
          echo "📊 Job Cleanup Summary:"
          echo "- Removed jobs older than 30 days"
          echo "- Deactivated expired job listings"
          echo ""
          echo "✅ Cleanup process completed"
