name: Seed Job Listings

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "seed-jobs" to confirm seeding'
        required: true
        default: ''

jobs:
  seed-jobs:
    name: Seed 50 Job Listings
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "seed-jobs" ]; then
            echo "❌ Confirmation failed. Please type 'seed-jobs' to confirm."
            exit 1
          fi
          echo "✅ Confirmation validated"
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link Supabase project
        run: |
          supabase link --project-ref ${{ secrets.VITE_SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Deploy seed-jobs function (if needed)
        run: |
          supabase functions deploy seed-jobs
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Invoke seed-jobs function
        run: |
          echo "🌱 Seeding job listings..."
          response=$(curl -s -X POST \
            "${{ secrets.VITE_SUPABASE_URL }}/functions/v1/seed-jobs" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json")
          
          echo "Response: $response"
          
          # Check if response contains success
          if echo "$response" | grep -q "success.*true"; then
            echo "✅ Job listings seeded successfully!"
          else
            echo "❌ Failed to seed job listings"
            exit 1
          fi
      
      - name: Summary
        run: |
          echo "📊 Job Seeding Summary:"
          echo "- 25 South African job listings"
          echo "- 25 Nigerian job listings"
          echo "- Total: 50 job listings"
          echo ""
          echo "✅ All jobs have been seeded to the database"
